### ISSUE TITLE
这个可以跨平台吗，安卓的可以使用吗

### ISSUE THREAD

**Issue by IMLaoJI** [liumingmusic/react-native_toiletApp#1]
您弄的是ios端的。我想运行在安卓上如何实现呢

**Comment by liumingmusic** [comment]
目前不能再安卓上面运行，只能在ios上面。

**Comment by liumingmusic** [comment]
目前的版本已经可以支持android了

**Comment by alpbeg** [comment]
你好，几个星期前下载你的这个项目，但是服务端有问题呢。1.模块设置不能发布文章，没什么反映。2.分类中只有it的文章显示所有的分类。但是你提供的ip没问题，3, 本地服务器连接不到了。本地服务器有那样的问题， 请你帮一下。qq | WeChat：295415322 我需要你的帮助

**Comment by liumingmusic** [comment]
@alpbeg 模块设置功能还没有完全完善，你可以根据自己的业务需求进行完善功能，可能ios年不能使用http请求数据信息，还有本地有时候不能进行数据访问，你所指向的api都是发布在外网的。

**Comment by liumingmusic** [comment]
@alpbeg  我有时间也把你说的 功能完善一下。
