### ISSUE TITLE
关于登陆。

### ISSUE THREAD

**Issue by smm113522** [liumingmusic/react-native_toiletApp#3]
接口可以用。但是后台登录怎么进入，用户名和密码是多少，是不是没有user文件。

**Comment by liumingmusic** [comment]
admin/123456

在 2017-01-25 15:40:01，"smm113522" <notifications@github.com> 写道：


接口可以用。但是后台登录怎么进入，用户名和密码是多少，是不是没有user文件。

**Comment by liumingmusic** [comment]
admin/123456;你看看接口里面的就明白，不需要一个一个问啊。
