### ISSUE TITLE
无法顺利打开app

### ISSUE THREAD

**Issue by dtm-labs** [liumingmusic/react-native_toiletApp#4]
![image](https://cloud.githubusercontent.com/assets/6055142/23336583/f0f647a6-fc0e-11e6-9cc7-1da76a66e4ae.png)
开发时，无法正常打开app

**Comment by liumingmusic** [comment]
请安文档上面的步骤进行，最好使用npm

**Comment by dtm-labs** [comment]
使用npm安装后就好了，谢谢
