### ISSUE TITLE
Android调试运行问题：SyntaxError: Strict mode does not allow function declarations in a lexically nested statement

### ISSUE THREAD

**Issue by sephilex** [liumingmusic/react-native_toiletApp#5]
ios正常运行，安卓打包成release的apk也可以正常运行，debug就红屏报错：SyntaxError: Strict mode does not allow function declarations in a lexically nested statement。
除了加入local.properties文件，配置了密钥，工程文件无其它改动

**Comment by liumingmusic** [comment]
可能是你的语法有问题，需要进一步查看
